# Generated by Django 4.2.4 on 2024-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=20)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField()),
                ('task_assign_date', models.DateField()),
            ],
        ),
    ]
