# Generated by Django 4.2.4 on 2024-06-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_category_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='task_title',
        ),
    ]
